Refs #6896 Added parser-generator roundtrip test.
eProsima/xtypes pull request #49
Opened 2019-12-18 10:30 UTC by LuisGP

Small fixes were needed to pass it ;).

2019-12-18 10:33 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=41)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/41/)

2019-12-18 10:56 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=44)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/44/)

2019-12-18 10:57 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=45)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/45/)

2019-12-26 09:47 UTC, richiware requested changes

2019-12-26 09:47 UTC, richiware commented on include/xtypes/Module.hpp
> +            return static_cast<const EnumerationType<uint32_t>&>(*enumerations_32_.end()->second);
Use `xtypes_assert`.

2019-12-26 09:47 UTC, richiware commented on include/xtypes/Module.hpp
> +        return static_cast<const EnumerationType<uint32_t>&>(*enumerations_32_.end()->second);
Use `xtypes_assert`.

2020-01-07 07:27 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=53)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/53/)

2020-01-08 07:55 UTC, lemunozm requested changes

2020-01-08 07:55 UTC, lemunozm commented on include/xtypes/Module.hpp
> +            const std::string& submodule) const
:D

2020-01-08 07:55 UTC, lemunozm commented on include/xtypes/Module.hpp
> +            bool from_enumeration = false)
Maybe I don't understand it well, but, don't you catch the enumeration type from the DynamicData kind?

2020-01-08 07:55 UTC, lemunozm commented on include/xtypes/Module.hpp
> +            // This will fail
so... should be an assert here?

2020-01-08 07:55 UTC, lemunozm commented on include/xtypes/Module.hpp
> +        // This will fail
also here?

2020-01-08 08:18 UTC, LuisGP commented on include/xtypes/Module.hpp
> +            bool from_enumeration = false)
Yes... and not. This parameter isn't for constants created from an enumeration, but for "tricky" constants automatically created with the enumeration values by the parser.

For example, in the following IDL:
```idl
enum MyEnum
{
    A,
    B
};

struct MyStruct
{
    uint32 int_array[B];
};
```
The symbol `B` must be accessible and have the correct value in order to create the array as expected. To do so, the parser creates two constants in the current Module, `MyEnum::B` and `B` (the same for `A`, obviously). These constants aren't created by the user, and the generator must ignore them.

2020-01-08 08:18 UTC, LuisGP commented on include/xtypes/Module.hpp
> +            // This will fail
Please, see the latest version of the file :).

2020-01-08 08:18 UTC, LuisGP commented on include/xtypes/Module.hpp
> +        // This will fail
Again, update the branch.

2020-01-10 07:54 UTC, richiware approved these changes

2020-01-10 07:55 UTC, merged