Refs #6916 Added log to IDL parser.
eProsima/xtypes pull request #50
Opened 2019-12-19 08:39 UTC by LuisGP

This PR adds the logging feature to the parser, including:
- Implementation
- Testing
- Documentation

A potential example could be implemented along with a parser example. A standalone `Log` example doesn't make sense to me.

2019-12-19 08:42 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=46)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/46/)

2019-12-19 08:43 UTC, LuisGP commented
The Jenkins job failed because it is expecting the *not yet merged* generator-parser roundtrip test.

2019-12-26 09:31 UTC, richiware requested changes

2019-12-26 09:31 UTC, richiware commented on README.md
> +If strict is set to true, then it will return **only** LogEvents with the same LogLevel. Else (default),
```suggestion
If `strict` is set to true, then it will return **only** LogEvents with the same LogLevel. Else (default),
```

2020-01-07 08:14 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=54)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/54/)

2020-01-07 08:22 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=55)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/55/)

2020-01-07 08:29 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=56)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/56/)

2020-01-07 08:34 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=57)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/57/)

2020-01-08 08:30 UTC, richiware approved these changes

2020-01-08 08:30 UTC, merged