Bug fix: SequenceInstance::resize not allocating new members
eProsima/xtypes pull request #59
Opened 2020-01-14 11:46 UTC by jamoralp

Fix for `resize` using wrong address across iterations (it remained unchanged). Added test to perform resizes based on complex DynamicData sequences (sequence of StructType with several members).

2020-01-14 11:49 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=67)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/67/)

2020-01-14 12:52 UTC, LuisGP submitted a review, later dismissed
LGTM

2020-01-14 15:29 UTC, richiware requested changes

2020-01-14 15:29 UTC, richiware commented on include/xtypes/SequenceInstance.hpp
> +        uint8_t* place;
Why not declarate variable inside loop? In this case the scope is more clear.

2020-01-15 06:16 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=68)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/68/)

2020-01-15 06:19 UTC, LuisGP approved these changes

2020-01-15 07:37 UTC, richiware approved these changes

2020-01-15 07:37 UTC, merged