MapType
eProsima/xtypes pull request #60
Opened 2020-01-17 10:46 UTC by LuisGP

This PR adds the MapType to xtypes. Includes:
- PairType Implementation: Used as MapType's content.
- Instanceable hash method: Used for hashing map's key values.
- MapType Implementation.
- MapType Tests.
- MapType parser integration and test.
- MapType generator integration and roundtrip test.
- MapType example.
- MapType & PairType documentation.

2020-01-17 10:50 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=75)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/75/)

2020-01-17 11:13 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=77)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/77/)

2020-01-21 13:22 UTC, richiware requested changes

2020-01-21 13:22 UTC, richiware commented on README.md
>    (for read-write operations).
Refresh the types which are collections

2020-01-21 13:22 UTC, richiware commented on README.md
> +  In a similar way as in the C++11 map iterator, a `PairType` instance is returned.
I miss something like "In the particular case of `MapType`,"...

2020-01-21 13:22 UTC, richiware commented on include/xtypes/ArrayType.hpp
> +            uint64_t h = content_type().hash(instance);
execute only if dimensions_ > 0

2020-01-21 13:22 UTC, richiware commented on include/xtypes/DynamicData.hpp
> +            "operator[const DynamicData&] is only available for MapType.");
The message should be about `at()` function, not `operator[]`.

2020-01-21 13:22 UTC, richiware commented on include/xtypes/DynamicData.hpp
> +            uint8_t* result = map.insert_instance(instance_, new_entry);
This if it is possible fist call `insert_instance` and then copy data in `result`. Then we avoid using a array in the stack.

2020-01-21 13:22 UTC, richiware commented on include/xtypes/MapInstance.hpp
> +            const PairType& content,
Better copy the content from the other map.

2020-01-21 13:22 UTC, richiware commented on include/xtypes/MapInstance.hpp
> +        if(content_.first().is_constructed_type() || content_.second().is_constructed_type())
```suggestion
        if(content_.first().is_constructed_type() && content_.second().is_constructed_type())
```

But check in `else` both are primitives. If not, return error.

2020-01-21 13:22 UTC, richiware commented on include/xtypes/MapInstance.hpp
> +        if(content_.first().is_constructed_type()
Wrong conditional. You can end in `else` with a constructed_type.

2020-01-21 13:22 UTC, richiware commented on include/xtypes/MapInstance.hpp
> +        if(content_.first().is_constructed_type() || content_.second().is_constructed_type())
Wrong conditional.

2020-01-21 13:22 UTC, richiware commented on include/xtypes/MapInstance.hpp
> +        uint64_t h = content_.hash(memory_);
Check size > 0

2020-01-21 13:22 UTC, richiware commented on include/xtypes/SequenceType.hpp
> +            uint64_t h = content_type().hash(instance);
check size

2020-01-21 13:22 UTC, richiware commented on test/unitary/parser/parser_test.cpp
> +            map<MyEnum, KeyStruct> map_5;
Can you test a map inside a map?

2020-01-21 13:27 UTC, LuisGP commented on include/xtypes/ArrayType.hpp
> +            uint64_t h = content_type().hash(instance);
Nice catch

2020-01-21 13:38 UTC, LuisGP commented on include/xtypes/MapInstance.hpp
> +        if(content_.first().is_constructed_type() || content_.second().is_constructed_type())
Not in this case. We are comparing `PairType` instances. We check the components of the pair just to try the optimization.

2020-01-21 13:41 UTC, LuisGP commented on include/xtypes/MapInstance.hpp
> +        if(content_.first().is_constructed_type()
No, you can't. If any of the types of the pair is constructed, then it will enter the `if` branch.

2020-01-21 13:44 UTC, LuisGP commented on include/xtypes/MapInstance.hpp
> +        if(content_.first().is_constructed_type() || content_.second().is_constructed_type())
Remember, we *move* `PairType`, so here, we are just comparing the `PairType` contents to try the optimization. I think the conditional is OK.

2020-01-21 14:23 UTC, LuisGP commented on include/xtypes/DynamicData.hpp
> +            uint8_t* result = map.insert_instance(instance_, new_entry);
<3

2020-01-21 14:28 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=79)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/79/)

2020-01-21 15:13 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=80)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/80/)

2020-01-21 15:18 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=81)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/81/)

2020-01-21 15:26 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=82)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/82/)

2020-01-22 06:13 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=85)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/85/)

2020-01-22 06:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=87)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/87/)

2020-01-22 06:57 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=88)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/88/)

2020-01-22 11:17 UTC, richiware approved these changes

2020-01-22 11:34 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=90)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/90/)

2020-01-22 11:42 UTC, richiware commented
Leak errors are from master branch.

2020-01-22 11:42 UTC, merged