Add Command line IDL Parser Tool
eProsima/xtypes pull request #87
Opened 2021-03-26 11:18 UTC by laura-eprosima

2021-03-26 11:25 UTC, jamoralp requested changes

2021-03-26 11:25 UTC, jamoralp commented on tools/idl_validator.cpp
> +    if (argc == 1)
```suggestion
    if (argc != 2)
```

2021-03-26 11:25 UTC, jamoralp commented on tools/idl_validator.cpp
> +    else if (argc == 2)
```suggestion
    else
```

2021-03-26 12:09 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=158)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/158/)

2021-03-29 05:27 UTC, jamoralp approved these changes

2021-03-29 05:31 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=xtypes-manual-linux&build=159)](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/159/)

2021-03-29 05:32 UTC, merged